[package]
name = "my-coin"
version = "0.0.0"

[addresses]
MyCoinAddress = "0xac3e5a1bda65d73b1b893892548578f7"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda180af40a8b3e26c0c7b548c4c290cd7e7"}

